import { NextResponse } from "next/server";
import { createAdminClient, adminConfigured } from "@/lib/supabase/admin";
import { assertReportAccess, currentUserId } from "@/lib/commerce/entitlements";
import { sendPurchaseEmail } from "@/lib/email/purchase.server";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/**
 * POST /api/report/[id]/email
 *
 * Send the creator their own report link. Used by the ownership module once
 * a creator is verified, so "email me this report" does not ask for an
 * address the system already has.
 *
 * Authorization is the ordinary one: the caller must hold a session that is
 * entitled to THIS scan. The destination is resolved server-side and the CTA
 * is a secure return link generated by the auth service, so the email proves
 * identity rather than carrying access. Nobody can use this to mail someone
 * else's report anywhere.
 *
 * Reuses the existing transactional sender rather than adding a second one —
 * its copy ("Your Song Intelligence is ready") is already correct for both a
 * free first report and a paid one.
 */
export async function POST(
  _req: Request,
  { params }: { params: { id: string } },
) {
  const scanId = params.id;

  const access = await assertReportAccess(scanId);
  if (!access.ok) {
    // Same opaque refusal the report route gives: no enumeration.
    return NextResponse.json({ error: "forbidden" }, { status: 403 });
  }

  const userId = await currentUserId();
  if (!userId) return NextResponse.json({ error: "forbidden" }, { status: 403 });
  if (!adminConfigured()) {
    return NextResponse.json({ error: "not_configured" }, { status: 503 });
  }

  const result = await sendPurchaseEmail(createAdminClient(), {
    userId,
    offer: "song_intelligence",
    scanId,
  });

  if (!result.ok) {
    console.error(`[report email] not sent for ${scanId}: ${result.reason}`);
    return NextResponse.json({ error: result.reason }, { status: 503 });
  }
  return NextResponse.json({ ok: true });
}
